# Example docker-compose.yml file
version: '2'
services:
  notebooks:
    build:
      context: .
      dockerfile: Dockerfile
    # env_file: .env
    ports:
      - "8888:8888"
      - "6006:6006"
    volumes:
    - .:/src/Patch_ana
    - .:/notebooks
    - ./archive:/tensorboard
    - /Users/Shuang/Dropbox/Andreas' Lab/Server Data/Shuang/Processed_test:/data
    # - /Volumes/lab/Shuang/Processed_test:/data
